name: deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd ./threexel-war-front && npm i

      - name: Build project
        run: cd ./threexel-war-front && npm run build

      - name: List files in dist directory
        run: cd ./threexel-war-front && ls -la dist

      - name: copy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "threexel-war-front/dist/*"
          target: ~/threexel-war/threexel-war-front/dist

      - name: SSH into server and execute commands
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ./threexel-war/
            git pull
            cd ./threexel-war-front
            npm i
            cd ../threexel-war-back/
            npm i
            npx prisma migrate reset -f
            npm run build
            pm2 restart threewel-war

